### ISSUE TITLE
Where does it drop the good nitro codes?

### ISSUE THREAD

**Issue by kevlu8** [8qBITs/NitroGen#1]
Where does it drop the valid nitro codes? Theres no txt file with any label that looks like "valid codes" and it also clears the screen every ~1 second, so where would valid codes go?

**Comment by xKatooo** [comment]
> Where does it drop the valid nitro codes? Theres no txt file with any label that looks like "valid codes" and it also clears the screen every ~1 second, so where would valid codes go?

Apparently it generates codes and checks them in a discord API, it returns something like subscription or access denied and this is the response it takes to know if it works or not

**Comment by 8qBITs** [comment]
Indeed, and then if it's valid it gets thrown into the file.
